services:
  - type: web
    name: 5v5-football-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src
      sizeGB: 1